### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by rogeriodeoliveira** [hash3liZer/wifijammer#10]
Command: 
`python3 wifijammer.py -i wlan1mon -a 0C:0B:0E:09:0D:08,d8:00:00:02:0d:04 --aggressive`
Error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/jammer/wifijammer-SSIDs-list/wifijammer.py", line 299, in jammer
    subprocess.call(['iwconfig', self.interface, 'channel', str(ch)])
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1752, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory

```
The process increases the memory usage, reaching the ram limit, causing the error

**Comment by kelvinkbk** [comment]
Interface not found
