### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by DrewRidley** [hash3liZer/wifijammer#11]
Error for wireless request "Set Frequency" (8B04) :
    SET failed on device wlx08bd4378e8a6 ; Operation not permitted.
Traceback (most recent call last):
  File "wifijammer.py", line 491, in <module>
    main()
  File "wifijammer.py", line 487, in main
    jammer.engage()
  File "wifijammer.py", line 330, in engage
    sniff(iface=self.interface, prn=self.injector)
  File "/home/drewr/.local/lib/python3.8/site-packages/scapy/sendrecv.py", line 972, in sniff
    sniffer._run(*args, **kwargs)
  File "/home/drewr/.local/lib/python3.8/site-packages/scapy/sendrecv.py", line 841, in _run
    sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
  File "/home/drewr/.local/lib/python3.8/site-packages/scapy/arch/linux.py", line 467, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted

**Comment by SirKnightV** [comment]
try sudo chmod +x * (inside the dir of wifijammer) , later try sudo su , later sudo python3 <command>
