### ISSUE TITLE
UnboundLocalError: cannot access local variable 'f' where it is not associated with a value

### ISSUE THREAD

**Issue by Prakash9771** [hash3liZer/wifijammer#17]
$ python3 wifijammer.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/scapy/arch/linux.py", line 125, in get_if_list
    f = open("/proc/net/dev", "rb")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/proc/net/dev'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/wifijammer/wifijammer.py", line 14, in <module>
    from scapy.sendrecv import sniff
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/scapy/sendrecv.py", line 35, in <module>
    import scapy.route  # noqa: F401
    ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/scapy/route.py", line 203, in <module>
    conf.iface = get_working_if()
                 ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/scapy/arch/linux.py", line 144, in get_working_if
    for i in get_if_list():
             ^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/scapy/arch/linux.py", line 127, in get_if_list
    f.close()
    ^
UnboundLocalError: cannot access local variable 'f' where it is not associated with a value

**Comment by dkirichev** [comment]
It's a permission error. Try:
```
sudo python3 wifijammer.py
``` 
This might resolve the issue. Unfortunately the script doesn't handle permission errors
